// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG4n4GMEZX-L6-aulzOJrR5KJEGoo3X0c',
    appId: '1:260469857067:web:baa99546a74a539e12c36e',
    messagingSenderId: '260469857067',
    projectId: 'catalog-app-1f493',
    authDomain: 'catalog-app-1f493.firebaseapp.com',
    storageBucket: 'catalog-app-1f493.appspot.com',
    measurementId: 'G-5P6VKES9ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTyj8rLN9kxV064fC3bRlBrpBt28Z0IKM',
    appId: '1:260469857067:android:b8b450129fa01d5412c36e',
    messagingSenderId: '260469857067',
    projectId: 'catalog-app-1f493',
    storageBucket: 'catalog-app-1f493.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtgFdU_-vfTo5aoNMkL8845Bj7xtT8PYo',
    appId: '1:260469857067:ios:d3c4c8297949697d12c36e',
    messagingSenderId: '260469857067',
    projectId: 'catalog-app-1f493',
    storageBucket: 'catalog-app-1f493.appspot.com',
    iosClientId: '260469857067-grcfs8echcs5uhsjs9o1ja7ql049j0ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtgFdU_-vfTo5aoNMkL8845Bj7xtT8PYo',
    appId: '1:260469857067:ios:d3c4c8297949697d12c36e',
    messagingSenderId: '260469857067',
    projectId: 'catalog-app-1f493',
    storageBucket: 'catalog-app-1f493.appspot.com',
    iosClientId: '260469857067-grcfs8echcs5uhsjs9o1ja7ql049j0ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
